name: yandex_js_maps
description: A Flutter Web plugin for integrating Yandex Maps JS API using Dart JS interop.
version: 1.0.1
homepage: https://github.com/ignatuschka/yandex_js_maps
repository: https://github.com/ignatuschka/yandex_js_maps
issue_tracker: https://github.com/ignatuschka/yandex_js_maps/issues
documentation: https://github.com/ignatuschka/yandex_js_maps#readme
topics:
  - flutter
  - web
  - maps
  - yandex
  - plugin

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: YandexJsMapsWeb
        fileName: yandex_js_maps_web.dart